### ISSUE TITLE
When I run the devPipeline job, I get an error. What am I doing wrong?

### ISSUE THREAD

**Issue by andreicristianpetcu** [liatrio/pipeline-developer#2]
This is the error I get:

```
Started by upstream project "pipeline-updater" build number 4
originally caused by:
 Started by user anonymous
Started by user anonymous
ERROR: Could not find any definition of libraries [ldop-shared-library@fd16602cad0f97ca1b04090f93a0540ddc871b45]
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
WorkflowScript: Loading libraries failed

1 error

	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:310)
	at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1085)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:603)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:581)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:558)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:298)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:268)
	at groovy.lang.GroovyShell.parseClass(GroovyShell.java:688)
	at groovy.lang.GroovyShell.parse(GroovyShell.java:700)
	at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell.doParse(CpsGroovyShell.java:129)
	at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell.reparse(CpsGroovyShell.java:123)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.parseScript(CpsFlowExecution.java:516)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.start(CpsFlowExecution.java:479)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:268)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:415)
Finished: FAILURE
```

Am I doing something wrong or is the documentation not up to date?

Thank you!

**Comment by stein321** [comment]
Hey @andreicristianpetcu, that example repo has started being used by other members of my team for pipelines that require external libraries. I'm working on a new sample repo today that should resolve this issue. I'll keep you posted.

**Comment by stein321** [comment]
@andreicristianpetcu I created a new repo with a simple jenkins file that should work on any jenkins instance with docker agent access. I also update pipeline-developer with the new name of the sample repo. I'm updating the blog now with the new location of the sample repo.

**Comment by stein321** [comment]
Updated the blog post. @andreicristianpetcu can you try using https://github.com/liatrio/sample-pipeline-spring-petclinic instead of https://github.com/liatrio/spring-petclinic ? Let me know if you have any other issues.

**Comment by andreicristianpetcu** [comment]
I will test this out tomorrow! Thank you @stein321!

**Comment by andreicristianpetcu** [comment]
It worked! Thank you!

**Comment by stein321** [comment]
good to hear @andreicristianpetcu . Feel free to comment on how you are using it and if there are any additional features you'd like to see.
