### ISSUE TITLE
Cannot run program "/bin/sh" (in directory "/pipeline-dev") 

### ISSUE THREAD

**Issue by xech3l0nx** [liatrio/pipeline-developer#3]
```
Logs
Started by user anonymous
[EnvInject] - Loading node environment variables.
Building in workspace /pipeline-dev
[/pipeline-dev] $ /bin/sh -xe /tmp/jenkins7673853313425684272.sh
FATAL: command execution failed
java.io.IOException: error=20, Not a directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
Caused: java.io.IOException: Cannot run program "/bin/sh" (in directory "/pipeline-dev"): error=20, Not a directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at hudson.Proc$LocalProc.<init>(Proc.java:245)
	at hudson.Proc$LocalProc.<init>(Proc.java:214)
	at hudson.Launcher$LocalLauncher.launch(Launcher.java:858)
	at hudson.Launcher$ProcStarter.start(Launcher.java:385)
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:109)
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:66)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:730)
	at hudson.model.Build$BuildExecution.build(Build.java:206)
	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:490)
	at hudson.model.Run.execute(Run.java:1735)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:415)
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

**Comment by stein321** [comment]
thanks @xech3l0nx I'll have some time to look at this in the morning.

**Comment by stein321** [comment]
@xech3l0nx can you give me any more info on when that occurs?

**Comment by stein321** [comment]
Unable to reproduce
